"""Seed connector providing realistic, high-relevance opportunities tailored to candidate's profile."""

from datetime import datetime, timedelta
from typing import Any, Dict, List
from agent.connectors.base import BaseConnector


class MockSeedConnector(BaseConnector):
    """Provides initial realistic job postings and recruitment signals for demonstration and testing."""

    @property
    def source_name(self) -> str:
        return "LinkedIn & Public Signals"

    def search_jobs(self, query: str = "", location: str = "Hyderabad", limit: int = 10) -> List[Dict[str, Any]]:
        now = datetime.utcnow()
        return [
            {
                "company": "Tiger Analytics",
                "job_title": "Azure Data Engineer (Databricks & PySpark)",
                "location": "Hyderabad",
                "work_mode": "Hybrid",
                "sources": ["LinkedIn Posts", "Tiger Analytics Careers"],
                "job_url": "https://www.linkedin.com/jobs/view/tiger-analytics-azure-data-engineer-hyd-101",
                "posted_date": (now - timedelta(hours=6)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "<24h",
                "deadline": "Rolling",
                "experience_required": "0-2 years (2025 batch welcome)",
                "salary": "₹8 - 14 LPA",
                "skills": "Databricks, PySpark, Azure Data Factory (ADF), Delta Lake, SQL, Python, ADLS Gen2",
                "description": "Looking for energetic Data Engineers with strong foundations in Azure, Databricks, and PySpark. Candidate will design metadata-driven pipelines, migrate SQL Server data to Delta Lake, and implement Unity Catalog governance.",
                "recruitment_signal": "Active Recruitment Signal",
                "recruitment_signal_date": (now - timedelta(hours=6)).strftime("%Y-%m-%d"),
                "application_method": "LinkedIn DM / Direct HR Email",
                "contact_email": "ta.data@tigeranalytics.com",
            },
            {
                "company": "LTIMindtree",
                "job_title": "Data Engineer - Databricks & PySpark",
                "location": "Hyderabad",
                "work_mode": "Hybrid",
                "sources": ["LinkedIn Posts", "Naukri"],
                "job_url": "https://www.linkedin.com/jobs/view/ltimindtree-databricks-pyspark-hyd-102",
                "posted_date": (now - timedelta(hours=14)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "<24h",
                "deadline": "In 2 weeks",
                "experience_required": "0-3 years",
                "salary": "Competitive",
                "skills": "Databricks, PySpark, Python, Azure Data Engineering, SQL Server, Data Migration, ETL",
                "description": "Urgent hiring for Databricks Data Engineers in Hyderabad. Work on enterprise migration from legacy SQL Server to Lakehouse architecture using Databricks and Delta Lake.",
                "recruitment_signal": "Active Recruitment Signal",
                "recruitment_signal_date": (now - timedelta(hours=14)).strftime("%Y-%m-%d"),
                "application_method": "Share resume to recruiter",
                "contact_email": "careers.data@ltimindtree.com",
            },
            {
                "company": "Fractal Analytics",
                "job_title": "Cloud Data Engineer - Azure & GenAI Pipelines",
                "location": "Bengaluru / Remote India",
                "work_mode": "Remote",
                "sources": ["LinkedIn", "Company Careers"],
                "job_url": "https://www.linkedin.com/jobs/view/fractal-cloud-data-engineer-remote-103",
                "posted_date": (now - timedelta(hours=28)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "24-72h",
                "deadline": "Open until filled",
                "experience_required": "0-2 years",
                "salary": "₹10 - 16 LPA",
                "skills": "Azure, Databricks, PySpark, Python, Vector DBs, Delta Lake, LLM Data Engineering",
                "description": "Fractal is hiring early-career Data Engineers to build next-generation AI and Data Engineering pipelines. Experience with Databricks, Python, and Azure is preferred.",
                "recruitment_signal": "Normal Job Posting",
                "recruitment_signal_date": (now - timedelta(hours=28)).strftime("%Y-%m-%d"),
                "application_method": "Career Link",
                "contact_email": "",
            },
            {
                "company": "Celebal Technologies",
                "job_title": "Databricks Associate Data Engineer (2025 Passout Drive)",
                "location": "Jaipur / Pune / Remote",
                "work_mode": "Hybrid",
                "sources": ["LinkedIn Posts", "Recruitment Drive"],
                "job_url": "https://www.linkedin.com/posts/celebal-tech-offcampus-databricks-2025-104",
                "posted_date": (now - timedelta(hours=8)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "<24h",
                "deadline": "September 30",
                "experience_required": "2025 Graduates / Freshers",
                "salary": "₹6.5 - 9.5 LPA",
                "skills": "Databricks, PySpark, Azure, SQL, Python, Delta Lake",
                "description": "Celebal Technologies is conducting an exclusive off-campus drive for 2025 engineering graduates with skills in Databricks and Microsoft Azure. DM your resume or apply via link.",
                "recruitment_signal": "Campus/Off-Campus Hiring",
                "recruitment_signal_date": (now - timedelta(hours=8)).strftime("%Y-%m-%d"),
                "application_method": "Google Form / DM",
                "contact_email": "campus@celebaltech.com",
            },
            {
                "company": "Accenture India",
                "job_title": "Data Engineering Analyst - Azure & ADF",
                "location": "Hyderabad / Bengaluru",
                "work_mode": "Hybrid",
                "sources": ["Naukri", "LinkedIn"],
                "job_url": "https://www.naukri.com/job-listings-accenture-azure-data-engineering-analyst-105",
                "posted_date": (now - timedelta(days=2)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "24-72h",
                "deadline": "Rolling",
                "experience_required": "0-2 years",
                "salary": "Standard Industry",
                "skills": "Azure Data Factory, PySpark, SQL Server, ADLS Gen2, Data Reconciliation",
                "description": "Accenture Data & AI practice is hiring Data Analysts and Engineers. Responsibilities include building ELT workflows using ADF and PySpark on Azure.",
                "recruitment_signal": "Referral Opportunity",
                "recruitment_signal_date": (now - timedelta(days=2)).strftime("%Y-%m-%d"),
                "application_method": "Employee Referral / Portal",
                "contact_email": "",
            },
            {
                "company": "Cognizant",
                "job_title": "Walk-in Interview: PySpark & Databricks Engineers",
                "location": "Hyderabad (Gachibowli)",
                "work_mode": "On-site",
                "sources": ["LinkedIn Recruitment Post"],
                "job_url": "https://www.linkedin.com/posts/cognizant-hyderabad-walkin-databricks-106",
                "posted_date": (now - timedelta(hours=18)).strftime("%Y-%m-%d %H:%M"),
                "freshness_tier": "<24h",
                "deadline": "This Saturday",
                "experience_required": "0-3 years",
                "salary": "As per company standards",
                "skills": "PySpark, Databricks, SQL, Azure, ETL",
                "description": "Cognizant Hyderabad Walk-in Interview this Saturday for Data Engineers. Multiple openings for candidates with hands-on PySpark and Databricks project experience. Bring updated resume and ID proof.",
                "recruitment_signal": "Recruitment Event",
                "recruitment_signal_date": (now - timedelta(hours=18)).strftime("%Y-%m-%d"),
                "application_method": "Walk-in Interview Registration",
                "contact_email": "walkin.hyd@cognizant.com",
            },
        ]

    def search_signals(self, query: str = "", limit: int = 10) -> List[Dict[str, Any]]:
        now = datetime.utcnow()
        return [
            {
                "company": "Tiger Analytics",
                "person": "Ananya Sharma (Lead Technical Recruiter)",
                "author_profile_url": "https://www.linkedin.com/in/ananya-sharma-recruiter",
                "signal_type": "Active Recruitment Signal",
                "post_url": "https://www.linkedin.com/posts/ananya-sharma-tiger-analytics-hiring-de-101",
                "post_date": (now - timedelta(hours=6)).strftime("%Y-%m-%d %H:%M"),
                "freshness_hours": 6,
                "keywords": "Hiring, Databricks, PySpark, Hyderabad, DM resume",
                "role": "Azure Data Engineer",
                "location": "Hyderabad",
                "urgency": "Urgent",
                "relevance": 94.0,
                "evidence": "We are actively hiring 10+ Data Engineers for our Hyderabad office! Strong hands-on experience in Azure Databricks, PySpark, and Delta Lake required. Immediate joiners and 2025 batch grads with project experience can DM resume directly or email ta.data@tigeranalytics.com.",
                "application_method": "LinkedIn DM / Direct Email",
                "contact_email": "ta.data@tigeranalytics.com",
            },
            {
                "company": "Celebal Technologies",
                "person": "Rohan Verma (Campus Hiring Lead)",
                "author_profile_url": "https://www.linkedin.com/in/rohan-verma-campus-celebal",
                "signal_type": "Campus/Off-Campus Hiring",
                "post_url": "https://www.linkedin.com/posts/rohan-verma-celebal-offcampus-2025-102",
                "post_date": (now - timedelta(hours=8)).strftime("%Y-%m-%d %H:%M"),
                "freshness_hours": 8,
                "keywords": "Off-campus, 2025 batch, Databricks, Freshers",
                "role": "Databricks Associate Data Engineer",
                "location": "Jaipur / Pune / Remote",
                "urgency": "High",
                "relevance": 92.0,
                "evidence": "Announcement: Off-campus recruitment drive for 2025 engineering graduates! We are looking for passionate candidates skilled in Microsoft Azure and Databricks. Selected engineers will work on modern lakehouse migrations.",
                "application_method": "Google Form / Email",
                "contact_email": "campus@celebaltech.com",
            },
            {
                "company": "Cognizant",
                "person": "Pooja Reddy (Talent Acquisition Specialist)",
                "author_profile_url": "https://www.linkedin.com/in/pooja-reddy-cognizant-hyd",
                "signal_type": "Recruitment Event",
                "post_url": "https://www.linkedin.com/posts/pooja-reddy-cognizant-walkin-hyd-103",
                "post_date": (now - timedelta(hours=18)).strftime("%Y-%m-%d %H:%M"),
                "freshness_hours": 18,
                "keywords": "Walk-in, Hyderabad, PySpark, Databricks, Saturday",
                "role": "Data Engineer (PySpark / Databricks)",
                "location": "Hyderabad (Gachibowli)",
                "urgency": "Urgent",
                "relevance": 88.0,
                "evidence": "Walk-in interview this Saturday at Cognizant Hyderabad, Gachibowli Campus. Openings for Data Engineers with PySpark and Databricks skills. Registration starts at 9:30 AM.",
                "application_method": "Walk-in Drive",
                "contact_email": "walkin.hyd@cognizant.com",
            },
            {
                "company": "Accenture India",
                "person": "Vikram Iyer (Senior Data Engineer & LNMIIT '22 Alumni)",
                "author_profile_url": "https://www.linkedin.com/in/vikram-iyer-accenture-de",
                "signal_type": "Referral Opportunity",
                "post_url": "https://www.linkedin.com/posts/vikram-iyer-accenture-referrals-104",
                "post_date": (now - timedelta(days=1, hours=4)).strftime("%Y-%m-%d %H:%M"),
                "freshness_hours": 28,
                "keywords": "Referral, Data Engineer, Azure, ADF, DM me",
                "role": "Data Engineering Analyst",
                "location": "Hyderabad / Bengaluru",
                "urgency": "High",
                "relevance": 90.0,
                "evidence": "Happy to refer strong candidates for multiple Data Engineering positions at Accenture India. Looking for engineers with Azure, ADF, and SQL experience. DM me your resume with Job ID.",
                "application_method": "LinkedIn DM / Referral",
                "contact_email": "",
            },
        ]
